### ISSUE TITLE
最新版laravel安装报Target class [swift.transport] does not exist.

### ISSUE THREAD

**Issue by nfhh** [overtrue/laravel-mail-aliyun#11]
最新版laravel安装报Target class [swift.transport] does not exist.

**Comment by overtrue** [comment]
请试试 2.0 https://github.com/overtrue/laravel-mail-aliyun/releases/tag/2.0.0

<blockquote><img src="https://avatars1.githubusercontent.com/u/1472352?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/overtrue/laravel-mail-aliyun">overtrue/laravel-mail-aliyun</a></strong></div><div>:e-mail:  Aliyun DrirectMail Transport for Laravel Application. - overtrue/laravel-mail-aliyun</div></blockquote>
