### ISSUE TITLE
下的laravel最新版7.21.0

### ISSUE THREAD

**Issue by nfhh** [overtrue/laravel-mail-aliyun#13]
下的laravel最新版7.21.0报
[2020-07-25 08:44:50] local.ERROR: Expected response code 250 but got code "550", with message "550 5.7.1 Relaying denied
" {"exception":"[object] (Swift_TransportException(code: 550): Expected response code 250 but got code \"550\", with message \"550 5.7.1 Relaying denied
![image](https://user-images.githubusercontent.com/30310521/88453086-99dc7680-ce96-11ea-81ca-eba9e0ad103c.png)

**Comment by overtrue** [comment]
检查你的账号配置
